_ = {
  'gradients': {
    'red': '#ff0000@0.9',
    'white': '#ffffff@0.9',
    'text': '#ff0000@0.0',
  },
  'textures': {
    'text0': {
      'type': 'perlin',
      'size': 3000.,
      'octaves': 6,
      'persistence': 0.50,
      'percentage': 1.0,
      'scale': 50.,
      'range': [0.0, 0.0, 1.0, 1.0],
      'strength': 1.0,
      'rotation': 0.0,  // TODO: !
      'speed': 1.,
    },
    'text1': {
      'type': 'perlin',
      'size': 3000.,
      'octaves': 7,
      'persistence': 0.45,
      'percentage': 1.0,
      'scale': 100.,
      'range': [0.0, 0.0, 1.0, 1.0],
      'strength': 1.0,
      'speed': 1.,
    },
    'text2': {
      'type': 'fractal',
      'size': 3000.,
      'octaves': 3,
      'persistence': 0.50,
      'percentage': 0.8,
      'scale': 75.,
      'range': [0.0, 0.0, 1.0, 1.0],
      'strength': 1.0,
      'speed': 1.,
    },
    'text3': {
      'type': 'turbulence',
      'size': 3000.,
      'octaves': 4,
      'persistence': 0.50,
      'percentage': 0.8,
      'scale': 50 / 2,
      'range': [0.0, 0.0, 1.0, 1.0],
      'strength': 1.0,
      'speed': 1.,
    },
    'text4': {
      'type': 'turbulence',
      'size': 200.,
      'octaves': 4,
      'persistence': 0.50,
      'percentage': 0.8,
      'scale': 10,
      'range': [0.0, 0.0, 1.0, 1.0],
      'strength': 1.0,
      'speed': 1.,
    },
  },
  'objects': {
    'obj': {
      'type': 'circle',
      'blending_type': blending_type.normal,
      'gradient': 'white',
      'radius': 0,
      'radiussize': 200,
      'props': {},
      'init': function() {
        this.spawn({
          'id': 'text',
          'y': 250,
          'text': this.attr('text'),
        });
      },
    },
    'text': {
      'type': 'text',
      'gradient': 'text',
      'text': '',
      'text_size': 60,
      'text_align': 'center',
      'text_fixed': false,
    },
  },
  'video': {
    'fps': 25,
    'width': 1920,
    'height': 1080,
    'scale': 1.0,
    'init_scale': 0.5,
    'rand_seed': 1,
    'granularity': 100,
    'update_positions': false,
    'bg_color': {'r': 0., 'g': 0., 'b': 0., 'a': 1},
    'minimize_steps_per_object': false,
    'grain_for_opacity': false,
    'min_intermediates': 1,
    'max_intermediates': 1,
  },
  'scenes': [{
    'name': 'scene1',
    'duration': 5,
    'objects': [
      {
        'id': 'obj',
        'x': -600,
        'y': -250,
        'z': 0,
        'texture': 'text1',
        'seed': 2,
        'texture_3d': false,
        'attrs': {'text': 'perlin'}
      },
      {
        'id': 'obj',
        'x': 0,
        'y': -250,
        'z': 0,
        'texture': 'text2',
        'seed': 20,
        'texture_3d': false,
        'attrs': {'text': 'fractal'}
      },
      {
        'id': 'obj',
        'x': +600,
        'y': -250,
        'z': 0,
        'texture': 'text3',
        'seed': 3,
        'texture_3d': false,
        'attrs': {'text': 'turbulence'}
      },
      {
        'id': 'obj',
        'x': -600,
        'y': 250,
        'z': 0,
        'texture': 'text1',
        'seed': 2,
        'texture_3d': true,
        'attrs': {'text': '3D mapped'}
      },
      {
        'id': 'obj',
        'x': 0,
        'y': 250,
        'z': 0,
        'texture': 'text2',
        'seed': 20,
        'texture_3d': true,
        'attrs': {'text': '3D mapped'}
      },
      {
        'id': 'obj',
        'x': +600,
        'y': 250,
        'z': 0,
        'texture': 'text3',
        'seed': 3,
        'texture_3d': true,
        'attrs': {'text': '3D mapped'}
      },
    ],
  }]
};
