language: c++

sudo: required
dist: xenial

before_install:
  - sudo apt update -y
  - sudo apt install -y libpng16-16 libglu1-mesa libomp5

script:
  - make starcry_ubuntu1604

after_script:
  - ldd starcry
  - ./starcry --help
  - ./starcry input/test.js
  - make dockerize
