language: c++

services:
- docker

sudo: required
dist: focal

before_install:
  - sudo apt update -y
  - sudo apt install -y libpng16-16 libglu1-mesa libomp5

script:
  - make fast-docker-build
  - make client
  - make build_web

after_script:
  - ldd ./build/starcry
  - ./build/starcry --help
  - ./build/starcry input/test.js
  - make dockerize
