language: c++

sudo: required
dist: bionic

before_install:
  - git submodule update --init --recursive
  - sudo apt-get install -y gnupg2
  - echo deb http://apt.llvm.org/artful/ llvm-toolchain-artful-6.0 main | sudo tee -a /etc/apt/sources.list
  - echo deb-src http://apt.llvm.org/artful/ llvm-toolchain-artful-6.0 main | sudo tee -a /etc/apt/sources.list
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt update -y
  - sudo apt-get install -y clang-6.0 lldb-6.0 lld-6.0
#- echo deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main | sudo tee -a /etc/apt/sources.list
#- echo deb-src http://apt.llvm.org/bionic/ llvm-toolchain-bionic-7 main | sudo tee -a /etc/apt/sources.list
#- wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
#- sudo apt update -y
#- sudo apt-get install -y clang-7 lldb-7 lld-7
  - set -euxo pipefail; bash prepare_linux.sh

script: cmake -DSTATIC=1 -DLIB_PREFIX_DIR=/usr/local/src/starcry . && make -j $(nproc)

