language: c++

sudo: required
dist: bionic

before_install:
  - sudo apt update -y
  - sudo apt install -y libpng16-16 libglu1-mesa libomp5

script:
  - make

after_script:
  - ldd starcry
  - ./starcry --help
  - ./starcry input/test.js
  - echo temporary disabled-- make dockerize_ubuntu1604
