language: c++

sudo: required
dist: focal

before_install:
  - sudo apt update -y
  - sudo apt install -y libpng16-16 libglu1-mesa libomp5

script:
  - make

after_script:
  - ldd ./build/starcry
  - ./build/starcry --help
  - ./build/starcry input/test.js
  - make dockerize
