# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/trigen/projects/starcry

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/trigen/projects/starcry

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/trigen/projects/starcry/CMakeFiles /home/trigen/projects/starcry/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/trigen/projects/starcry/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named starcry

# Build rule for target.
starcry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 starcry
.PHONY : starcry

# fast build rule for target.
starcry/fast:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/build
.PHONY : starcry/fast

opt/cppse/build/v8pp/include/v8pp/context.o: opt/cppse/build/v8pp/include/v8pp/context.cpp.o

.PHONY : opt/cppse/build/v8pp/include/v8pp/context.o

# target to build an object file
opt/cppse/build/v8pp/include/v8pp/context.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/opt/cppse/build/v8pp/include/v8pp/context.cpp.o
.PHONY : opt/cppse/build/v8pp/include/v8pp/context.cpp.o

opt/cppse/build/v8pp/include/v8pp/context.i: opt/cppse/build/v8pp/include/v8pp/context.cpp.i

.PHONY : opt/cppse/build/v8pp/include/v8pp/context.i

# target to preprocess a source file
opt/cppse/build/v8pp/include/v8pp/context.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/opt/cppse/build/v8pp/include/v8pp/context.cpp.i
.PHONY : opt/cppse/build/v8pp/include/v8pp/context.cpp.i

opt/cppse/build/v8pp/include/v8pp/context.s: opt/cppse/build/v8pp/include/v8pp/context.cpp.s

.PHONY : opt/cppse/build/v8pp/include/v8pp/context.s

# target to generate assembly for a file
opt/cppse/build/v8pp/include/v8pp/context.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/opt/cppse/build/v8pp/include/v8pp/context.cpp.s
.PHONY : opt/cppse/build/v8pp/include/v8pp/context.cpp.s

src/job_generator.o: src/job_generator.cpp.o

.PHONY : src/job_generator.o

# target to build an object file
src/job_generator.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/job_generator.cpp.o
.PHONY : src/job_generator.cpp.o

src/job_generator.i: src/job_generator.cpp.i

.PHONY : src/job_generator.i

# target to preprocess a source file
src/job_generator.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/job_generator.cpp.i
.PHONY : src/job_generator.cpp.i

src/job_generator.s: src/job_generator.cpp.s

.PHONY : src/job_generator.s

# target to generate assembly for a file
src/job_generator.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/job_generator.cpp.s
.PHONY : src/job_generator.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/primitives.o: src/primitives.cpp.o

.PHONY : src/primitives.o

# target to build an object file
src/primitives.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/primitives.cpp.o
.PHONY : src/primitives.cpp.o

src/primitives.i: src/primitives.cpp.i

.PHONY : src/primitives.i

# target to preprocess a source file
src/primitives.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/primitives.cpp.i
.PHONY : src/primitives.cpp.i

src/primitives.s: src/primitives.cpp.s

.PHONY : src/primitives.s

# target to generate assembly for a file
src/primitives.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/primitives.cpp.s
.PHONY : src/primitives.cpp.s

src/primitives/circle.o: src/primitives/circle.cpp.o

.PHONY : src/primitives/circle.o

# target to build an object file
src/primitives/circle.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/primitives/circle.cpp.o
.PHONY : src/primitives/circle.cpp.o

src/primitives/circle.i: src/primitives/circle.cpp.i

.PHONY : src/primitives/circle.i

# target to preprocess a source file
src/primitives/circle.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/primitives/circle.cpp.i
.PHONY : src/primitives/circle.cpp.i

src/primitives/circle.s: src/primitives/circle.cpp.s

.PHONY : src/primitives/circle.s

# target to generate assembly for a file
src/primitives/circle.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/primitives/circle.cpp.s
.PHONY : src/primitives/circle.cpp.s

src/primitives/color.o: src/primitives/color.cpp.o

.PHONY : src/primitives/color.o

# target to build an object file
src/primitives/color.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/primitives/color.cpp.o
.PHONY : src/primitives/color.cpp.o

src/primitives/color.i: src/primitives/color.cpp.i

.PHONY : src/primitives/color.i

# target to preprocess a source file
src/primitives/color.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/primitives/color.cpp.i
.PHONY : src/primitives/color.cpp.i

src/primitives/color.s: src/primitives/color.cpp.s

.PHONY : src/primitives/color.s

# target to generate assembly for a file
src/primitives/color.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/primitives/color.cpp.s
.PHONY : src/primitives/color.cpp.s

src/primitives/gradient.o: src/primitives/gradient.cpp.o

.PHONY : src/primitives/gradient.o

# target to build an object file
src/primitives/gradient.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/primitives/gradient.cpp.o
.PHONY : src/primitives/gradient.cpp.o

src/primitives/gradient.i: src/primitives/gradient.cpp.i

.PHONY : src/primitives/gradient.i

# target to preprocess a source file
src/primitives/gradient.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/primitives/gradient.cpp.i
.PHONY : src/primitives/gradient.cpp.i

src/primitives/gradient.s: src/primitives/gradient.cpp.s

.PHONY : src/primitives/gradient.s

# target to generate assembly for a file
src/primitives/gradient.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/primitives/gradient.cpp.s
.PHONY : src/primitives/gradient.cpp.s

src/primitives/line.o: src/primitives/line.cpp.o

.PHONY : src/primitives/line.o

# target to build an object file
src/primitives/line.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/primitives/line.cpp.o
.PHONY : src/primitives/line.cpp.o

src/primitives/line.i: src/primitives/line.cpp.i

.PHONY : src/primitives/line.i

# target to preprocess a source file
src/primitives/line.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/primitives/line.cpp.i
.PHONY : src/primitives/line.cpp.i

src/primitives/line.s: src/primitives/line.cpp.s

.PHONY : src/primitives/line.s

# target to generate assembly for a file
src/primitives/line.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/primitives/line.cpp.s
.PHONY : src/primitives/line.cpp.s

src/primitives/rectangle.o: src/primitives/rectangle.cpp.o

.PHONY : src/primitives/rectangle.o

# target to build an object file
src/primitives/rectangle.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/primitives/rectangle.cpp.o
.PHONY : src/primitives/rectangle.cpp.o

src/primitives/rectangle.i: src/primitives/rectangle.cpp.i

.PHONY : src/primitives/rectangle.i

# target to preprocess a source file
src/primitives/rectangle.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/primitives/rectangle.cpp.i
.PHONY : src/primitives/rectangle.cpp.i

src/primitives/rectangle.s: src/primitives/rectangle.cpp.s

.PHONY : src/primitives/rectangle.s

# target to generate assembly for a file
src/primitives/rectangle.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/primitives/rectangle.cpp.s
.PHONY : src/primitives/rectangle.cpp.s

src/render_window.o: src/render_window.cpp.o

.PHONY : src/render_window.o

# target to build an object file
src/render_window.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/render_window.cpp.o
.PHONY : src/render_window.cpp.o

src/render_window.i: src/render_window.cpp.i

.PHONY : src/render_window.i

# target to preprocess a source file
src/render_window.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/render_window.cpp.i
.PHONY : src/render_window.cpp.i

src/render_window.s: src/render_window.cpp.s

.PHONY : src/render_window.s

# target to generate assembly for a file
src/render_window.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/render_window.cpp.s
.PHONY : src/render_window.cpp.s

src/renderer.o: src/renderer.cpp.o

.PHONY : src/renderer.o

# target to build an object file
src/renderer.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/renderer.cpp.o
.PHONY : src/renderer.cpp.o

src/renderer.i: src/renderer.cpp.i

.PHONY : src/renderer.i

# target to preprocess a source file
src/renderer.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/renderer.cpp.i
.PHONY : src/renderer.cpp.i

src/renderer.s: src/renderer.cpp.s

.PHONY : src/renderer.s

# target to generate assembly for a file
src/renderer.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/renderer.cpp.s
.PHONY : src/renderer.cpp.s

src/rendering_engine_wrapper.o: src/rendering_engine_wrapper.cpp.o

.PHONY : src/rendering_engine_wrapper.o

# target to build an object file
src/rendering_engine_wrapper.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/rendering_engine_wrapper.cpp.o
.PHONY : src/rendering_engine_wrapper.cpp.o

src/rendering_engine_wrapper.i: src/rendering_engine_wrapper.cpp.i

.PHONY : src/rendering_engine_wrapper.i

# target to preprocess a source file
src/rendering_engine_wrapper.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/rendering_engine_wrapper.cpp.i
.PHONY : src/rendering_engine_wrapper.cpp.i

src/rendering_engine_wrapper.s: src/rendering_engine_wrapper.cpp.s

.PHONY : src/rendering_engine_wrapper.s

# target to generate assembly for a file
src/rendering_engine_wrapper.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/rendering_engine_wrapper.cpp.s
.PHONY : src/rendering_engine_wrapper.cpp.s

src/scripting.o: src/scripting.cpp.o

.PHONY : src/scripting.o

# target to build an object file
src/scripting.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/scripting.cpp.o
.PHONY : src/scripting.cpp.o

src/scripting.i: src/scripting.cpp.i

.PHONY : src/scripting.i

# target to preprocess a source file
src/scripting.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/scripting.cpp.i
.PHONY : src/scripting.cpp.i

src/scripting.s: src/scripting.cpp.s

.PHONY : src/scripting.s

# target to generate assembly for a file
src/scripting.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/scripting.cpp.s
.PHONY : src/scripting.cpp.s

src/stdin_reader.o: src/stdin_reader.cpp.o

.PHONY : src/stdin_reader.o

# target to build an object file
src/stdin_reader.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/stdin_reader.cpp.o
.PHONY : src/stdin_reader.cpp.o

src/stdin_reader.i: src/stdin_reader.cpp.i

.PHONY : src/stdin_reader.i

# target to preprocess a source file
src/stdin_reader.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/stdin_reader.cpp.i
.PHONY : src/stdin_reader.cpp.i

src/stdin_reader.s: src/stdin_reader.cpp.s

.PHONY : src/stdin_reader.s

# target to generate assembly for a file
src/stdin_reader.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/stdin_reader.cpp.s
.PHONY : src/stdin_reader.cpp.s

src/streamer.o: src/streamer.cpp.o

.PHONY : src/streamer.o

# target to build an object file
src/streamer.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/streamer.cpp.o
.PHONY : src/streamer.cpp.o

src/streamer.i: src/streamer.cpp.i

.PHONY : src/streamer.i

# target to preprocess a source file
src/streamer.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/streamer.cpp.i
.PHONY : src/streamer.cpp.i

src/streamer.s: src/streamer.cpp.s

.PHONY : src/streamer.s

# target to generate assembly for a file
src/streamer.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/streamer.cpp.s
.PHONY : src/streamer.cpp.s

src/streamer_output/allegro5_window.o: src/streamer_output/allegro5_window.cpp.o

.PHONY : src/streamer_output/allegro5_window.o

# target to build an object file
src/streamer_output/allegro5_window.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/streamer_output/allegro5_window.cpp.o
.PHONY : src/streamer_output/allegro5_window.cpp.o

src/streamer_output/allegro5_window.i: src/streamer_output/allegro5_window.cpp.i

.PHONY : src/streamer_output/allegro5_window.i

# target to preprocess a source file
src/streamer_output/allegro5_window.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/streamer_output/allegro5_window.cpp.i
.PHONY : src/streamer_output/allegro5_window.cpp.i

src/streamer_output/allegro5_window.s: src/streamer_output/allegro5_window.cpp.s

.PHONY : src/streamer_output/allegro5_window.s

# target to generate assembly for a file
src/streamer_output/allegro5_window.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/streamer_output/allegro5_window.cpp.s
.PHONY : src/streamer_output/allegro5_window.cpp.s

src/streamer_output/ffmpeg_encode.o: src/streamer_output/ffmpeg_encode.cpp.o

.PHONY : src/streamer_output/ffmpeg_encode.o

# target to build an object file
src/streamer_output/ffmpeg_encode.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/streamer_output/ffmpeg_encode.cpp.o
.PHONY : src/streamer_output/ffmpeg_encode.cpp.o

src/streamer_output/ffmpeg_encode.i: src/streamer_output/ffmpeg_encode.cpp.i

.PHONY : src/streamer_output/ffmpeg_encode.i

# target to preprocess a source file
src/streamer_output/ffmpeg_encode.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/streamer_output/ffmpeg_encode.cpp.i
.PHONY : src/streamer_output/ffmpeg_encode.cpp.i

src/streamer_output/ffmpeg_encode.s: src/streamer_output/ffmpeg_encode.cpp.s

.PHONY : src/streamer_output/ffmpeg_encode.s

# target to generate assembly for a file
src/streamer_output/ffmpeg_encode.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/streamer_output/ffmpeg_encode.cpp.s
.PHONY : src/streamer_output/ffmpeg_encode.cpp.s

src/streamer_output/ffmpeg_stream.o: src/streamer_output/ffmpeg_stream.cpp.o

.PHONY : src/streamer_output/ffmpeg_stream.o

# target to build an object file
src/streamer_output/ffmpeg_stream.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/streamer_output/ffmpeg_stream.cpp.o
.PHONY : src/streamer_output/ffmpeg_stream.cpp.o

src/streamer_output/ffmpeg_stream.i: src/streamer_output/ffmpeg_stream.cpp.i

.PHONY : src/streamer_output/ffmpeg_stream.i

# target to preprocess a source file
src/streamer_output/ffmpeg_stream.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/streamer_output/ffmpeg_stream.cpp.i
.PHONY : src/streamer_output/ffmpeg_stream.cpp.i

src/streamer_output/ffmpeg_stream.s: src/streamer_output/ffmpeg_stream.cpp.s

.PHONY : src/streamer_output/ffmpeg_stream.s

# target to generate assembly for a file
src/streamer_output/ffmpeg_stream.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/streamer_output/ffmpeg_stream.cpp.s
.PHONY : src/streamer_output/ffmpeg_stream.cpp.s

src/streamer_output/ffmpeg_stream_hls.o: src/streamer_output/ffmpeg_stream_hls.cpp.o

.PHONY : src/streamer_output/ffmpeg_stream_hls.o

# target to build an object file
src/streamer_output/ffmpeg_stream_hls.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/streamer_output/ffmpeg_stream_hls.cpp.o
.PHONY : src/streamer_output/ffmpeg_stream_hls.cpp.o

src/streamer_output/ffmpeg_stream_hls.i: src/streamer_output/ffmpeg_stream_hls.cpp.i

.PHONY : src/streamer_output/ffmpeg_stream_hls.i

# target to preprocess a source file
src/streamer_output/ffmpeg_stream_hls.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/streamer_output/ffmpeg_stream_hls.cpp.i
.PHONY : src/streamer_output/ffmpeg_stream_hls.cpp.i

src/streamer_output/ffmpeg_stream_hls.s: src/streamer_output/ffmpeg_stream_hls.cpp.s

.PHONY : src/streamer_output/ffmpeg_stream_hls.s

# target to generate assembly for a file
src/streamer_output/ffmpeg_stream_hls.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/streamer_output/ffmpeg_stream_hls.cpp.s
.PHONY : src/streamer_output/ffmpeg_stream_hls.cpp.s

src/util/compress_vector.o: src/util/compress_vector.cpp.o

.PHONY : src/util/compress_vector.o

# target to build an object file
src/util/compress_vector.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/util/compress_vector.cpp.o
.PHONY : src/util/compress_vector.cpp.o

src/util/compress_vector.i: src/util/compress_vector.cpp.i

.PHONY : src/util/compress_vector.i

# target to preprocess a source file
src/util/compress_vector.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/util/compress_vector.cpp.i
.PHONY : src/util/compress_vector.cpp.i

src/util/compress_vector.s: src/util/compress_vector.cpp.s

.PHONY : src/util/compress_vector.s

# target to generate assembly for a file
src/util/compress_vector.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/util/compress_vector.cpp.s
.PHONY : src/util/compress_vector.cpp.s

src/util/memory_font.o: src/util/memory_font.cpp.o

.PHONY : src/util/memory_font.o

# target to build an object file
src/util/memory_font.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/util/memory_font.cpp.o
.PHONY : src/util/memory_font.cpp.o

src/util/memory_font.i: src/util/memory_font.cpp.i

.PHONY : src/util/memory_font.i

# target to preprocess a source file
src/util/memory_font.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/util/memory_font.cpp.i
.PHONY : src/util/memory_font.cpp.i

src/util/memory_font.s: src/util/memory_font.cpp.s

.PHONY : src/util/memory_font.s

# target to generate assembly for a file
src/util/memory_font.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/util/memory_font.cpp.s
.PHONY : src/util/memory_font.cpp.s

src/util/remote_actors.o: src/util/remote_actors.cpp.o

.PHONY : src/util/remote_actors.o

# target to build an object file
src/util/remote_actors.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/util/remote_actors.cpp.o
.PHONY : src/util/remote_actors.cpp.o

src/util/remote_actors.i: src/util/remote_actors.cpp.i

.PHONY : src/util/remote_actors.i

# target to preprocess a source file
src/util/remote_actors.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/util/remote_actors.cpp.i
.PHONY : src/util/remote_actors.cpp.i

src/util/remote_actors.s: src/util/remote_actors.cpp.s

.PHONY : src/util/remote_actors.s

# target to generate assembly for a file
src/util/remote_actors.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/util/remote_actors.cpp.s
.PHONY : src/util/remote_actors.cpp.s

src/webserver.o: src/webserver.cpp.o

.PHONY : src/webserver.o

# target to build an object file
src/webserver.cpp.o:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/webserver.cpp.o
.PHONY : src/webserver.cpp.o

src/webserver.i: src/webserver.cpp.i

.PHONY : src/webserver.i

# target to preprocess a source file
src/webserver.cpp.i:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/webserver.cpp.i
.PHONY : src/webserver.cpp.i

src/webserver.s: src/webserver.cpp.s

.PHONY : src/webserver.s

# target to generate assembly for a file
src/webserver.cpp.s:
	$(MAKE) -f CMakeFiles/starcry.dir/build.make CMakeFiles/starcry.dir/src/webserver.cpp.s
.PHONY : src/webserver.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... starcry"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... opt/cppse/build/v8pp/include/v8pp/context.o"
	@echo "... opt/cppse/build/v8pp/include/v8pp/context.i"
	@echo "... opt/cppse/build/v8pp/include/v8pp/context.s"
	@echo "... src/job_generator.o"
	@echo "... src/job_generator.i"
	@echo "... src/job_generator.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/primitives.o"
	@echo "... src/primitives.i"
	@echo "... src/primitives.s"
	@echo "... src/primitives/circle.o"
	@echo "... src/primitives/circle.i"
	@echo "... src/primitives/circle.s"
	@echo "... src/primitives/color.o"
	@echo "... src/primitives/color.i"
	@echo "... src/primitives/color.s"
	@echo "... src/primitives/gradient.o"
	@echo "... src/primitives/gradient.i"
	@echo "... src/primitives/gradient.s"
	@echo "... src/primitives/line.o"
	@echo "... src/primitives/line.i"
	@echo "... src/primitives/line.s"
	@echo "... src/primitives/rectangle.o"
	@echo "... src/primitives/rectangle.i"
	@echo "... src/primitives/rectangle.s"
	@echo "... src/render_window.o"
	@echo "... src/render_window.i"
	@echo "... src/render_window.s"
	@echo "... src/renderer.o"
	@echo "... src/renderer.i"
	@echo "... src/renderer.s"
	@echo "... src/rendering_engine_wrapper.o"
	@echo "... src/rendering_engine_wrapper.i"
	@echo "... src/rendering_engine_wrapper.s"
	@echo "... src/scripting.o"
	@echo "... src/scripting.i"
	@echo "... src/scripting.s"
	@echo "... src/stdin_reader.o"
	@echo "... src/stdin_reader.i"
	@echo "... src/stdin_reader.s"
	@echo "... src/streamer.o"
	@echo "... src/streamer.i"
	@echo "... src/streamer.s"
	@echo "... src/streamer_output/allegro5_window.o"
	@echo "... src/streamer_output/allegro5_window.i"
	@echo "... src/streamer_output/allegro5_window.s"
	@echo "... src/streamer_output/ffmpeg_encode.o"
	@echo "... src/streamer_output/ffmpeg_encode.i"
	@echo "... src/streamer_output/ffmpeg_encode.s"
	@echo "... src/streamer_output/ffmpeg_stream.o"
	@echo "... src/streamer_output/ffmpeg_stream.i"
	@echo "... src/streamer_output/ffmpeg_stream.s"
	@echo "... src/streamer_output/ffmpeg_stream_hls.o"
	@echo "... src/streamer_output/ffmpeg_stream_hls.i"
	@echo "... src/streamer_output/ffmpeg_stream_hls.s"
	@echo "... src/util/compress_vector.o"
	@echo "... src/util/compress_vector.i"
	@echo "... src/util/compress_vector.s"
	@echo "... src/util/memory_font.o"
	@echo "... src/util/memory_font.i"
	@echo "... src/util/memory_font.s"
	@echo "... src/util/remote_actors.o"
	@echo "... src/util/remote_actors.i"
	@echo "... src/util/remote_actors.s"
	@echo "... src/webserver.o"
	@echo "... src/webserver.i"
	@echo "... src/webserver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

