apiVersion: v1
kind: Namespace
metadata:
  name: starcry
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: starcry
  namespace: starcry
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: starcry
        tier: starcry
    spec:
      containers:
      - name: starcrycontainer
        image: rayburgemeestre/starcry:latest
        command: ["/starcry"]
        args: ["-i", "--notty"]
        workingDir: /workdir
        volumeMounts:
        - mountPath: /workdir
          name: workdir-volume
        imagePullPolicy: Always
        ports:
        - containerPort: 18080
          name: http
      volumes:
      - name: workdir-volume
        hostPath:
          path: /mnt2/NAS/projects/starcry
---
apiVersion: v1
kind: Service
metadata:
  name: starcry
  namespace: starcry
  labels:
    app: starcry
    tier: starcry
spec:
  type: NodePort
  ports:
  - port: 18080
    name: http
  selector:
    app: starcry
    tier: starcry
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.provider: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
  name: starcry
  namespace: starcry
spec:
  rules:
  - host: sc.cppse.nl
    http:
      paths:
      - backend:
          serviceName: starcry
          servicePort: 18080
        path: /
  tls:
  - hosts:
    - sc.cppse.nl
    secretName: starcry-tls
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: starcry
  namespace: starcry
spec:
  acme:
    config:
    - domains:
      - sc.cppse.nl
      http01:
        ingress: ""
        ingressClass: nginx
  commonName: ""
  dnsNames:
  - sc.cppse.nl
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: starcry-tls
