name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3
    - name: git submodule update --init --recursive
      run: git submodule update --init --recursive
    - name: make
      run: make
    - name: make build
      run: make build
    - name: make test
      run: make test
    - name: make download-integration-test-reference
      run: make download-integration-test-reference
    - name: make integration-test
      run: make integration-test
    - name: upload integration test artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-artifacts
        path: /home/runner/work/starcry/starcry/test/integration/last-run
        retention-days: 1
    - name: upload sc.log artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: starcry-log
        path: /home/runner/work/starcry/starcry/sc.log
        retention-days: 1
    - name: update apt
      run: sudo apt update
    - name: install npm
      run: sudo apt install -y npm
    - name: install quasar
      run: sudo npm i -g @quasar/cli
    - name: install doxygen
      run: sudo apt install -y doxygen
    - name: install sphinx + breathe + rtd theme
      run: pip install breathe sphinx_rtd_theme
    - name: make docs
      run: make docs
    - name: make build-web
      run: make build-web
    - name: make dockerize
      run: make dockerize
