FROM ubuntu:24.04

COPY . /

# Now that we got rid of the SFML dependency, this seems no longer required.
# RUN apt update && apt install mesa-common-dev libxrandr2 libgl1 ncurses-term -y && apt clean && apt autoremove -y

ENV TERM=xterm-16color

